name: openMod_Zuerich2018

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.5
  - notebook  # jupyter notebook
  - numpy=1.14.3
  - pandas=0.20.3
  - pyyaml=3.12
  - requests
  - sqlalchemy
  - Rtree=0.8.3
  - scikit-learn
  - scipy
  - ipywidgets
  - pip:
    - ding0==0.1.4
    - "--editable=git+git@github.com:openego/eGo.git@dev#egg=eGo --process-dependency-links"
    - "--editable=git+git@github.com:openego/oedialect.git@master#egg=oedialect"
    - "--editable=git+git@github.com:openego/ego.io.git@v0.4.0#egg=egoio"
    - "--editable=git+git@github.com:openego/PyPSA.git@dev#egg=pypsa"
    - "--editable=git+git@github.com:openego/eTraGo.git@0.5.1#egg=etrago" #  eTraGo==0.5.1
    - "--editable=git+git@github.com:openego/tsam.git@master#egg=tsam"
    - "--editable=git+git@github.com:openego/eDisGo.git@dev#egg=edisgo"
